[tox]
envlist = py39, py310, py311, py312, py313, py314, pypy3

[testenv]
changedir = {toxworkdir}
commands =
    coverage run --source=mt940 --omit=*/tests/* -m xmlrunner discover -s mt940.test {posargs}
commands_post =
    coverage report --omit=README.rst
    coverage xml --omit=README.rst
deps =
    coverage
    unittest-xml-reporting
passenv = *
